"""initial schema

Revision ID: 30a92be2f929
Revises: 
Create Date: 2026-08-15 14:06:33.802272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30a92be2f929"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "evaluation_queries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("min_price", sa.Float(), nullable=True),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "search_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("min_price", sa.Float(), nullable=True),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("fallback", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_search_logs_created_at", "search_logs", ["created_at"], unique=False
    )
    op.create_index("idx_search_logs_mode", "search_logs", ["mode"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_products_active_price", "products", ["is_active", "price"], unique=False
    )
    op.create_index("idx_products_brand", "products", ["brand"], unique=False)
    op.create_index(
        "idx_products_category_id", "products", ["category_id"], unique=False
    )
    op.create_index("idx_products_is_active", "products", ["is_active"], unique=False)
    op.create_index("idx_products_price", "products", ["price"], unique=False)
    op.create_index("idx_products_rating", "products", ["rating"], unique=False)
    op.create_table(
        "product_specifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("spec_key", sa.String(length=100), nullable=False),
        sa.Column("spec_value", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_specs_key", "product_specifications", ["spec_key"], unique=False
    )
    op.create_index(
        "idx_specs_product_id", "product_specifications", ["product_id"], unique=False
    )
    op.create_table(
        "relevance_judgments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("relevance", sa.Integer(), nullable=False),
        sa.CheckConstraint("relevance BETWEEN 0 AND 3", name="ck_relevance_range"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["query_id"], ["evaluation_queries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("query_id", "product_id", name="uq_judgment_query_product"),
    )
    op.create_index(
        "idx_judgments_product_id", "relevance_judgments", ["product_id"], unique=False
    )
    op.create_index(
        "idx_judgments_query_id", "relevance_judgments", ["query_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_judgments_query_id", table_name="relevance_judgments")
    op.drop_index("idx_judgments_product_id", table_name="relevance_judgments")
    op.drop_table("relevance_judgments")
    op.drop_index("idx_specs_product_id", table_name="product_specifications")
    op.drop_index("idx_specs_key", table_name="product_specifications")
    op.drop_table("product_specifications")
    op.drop_index("idx_products_rating", table_name="products")
    op.drop_index("idx_products_price", table_name="products")
    op.drop_index("idx_products_is_active", table_name="products")
    op.drop_index("idx_products_category_id", table_name="products")
    op.drop_index("idx_products_brand", table_name="products")
    op.drop_index("idx_products_active_price", table_name="products")
    op.drop_table("products")
    op.drop_index("idx_search_logs_mode", table_name="search_logs")
    op.drop_index("idx_search_logs_created_at", table_name="search_logs")
    op.drop_table("search_logs")
    op.drop_table("evaluation_queries")
    op.drop_table("categories")
    # ### end Alembic commands ###
